<?php

namespace AppBundle\Repository;

/**
 * ExpenseUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenseUserRepository extends \Doctrine\ORM\EntityRepository
{
}
