<?php

namespace AppBundle\Repository;

/**
 * expenseUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class expenseUsersRepository extends \Doctrine\ORM\EntityRepository
{
}
