<?php

namespace AppBundle\Repository;

/**
 * ExpenseSubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenseSubCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
